"""苏州鸟类图谱数据 - 30种常见鸟类"""

BIRDS_DATA = [
    {
        "id": 1,
        "name": "白头鹎",
        "pinyin": "bái tóu bēi",
        "scientific_name": "Pycnonotus sinensis",
        "english_name": "Chinese Bulbul",
        "category": "雀形目",
        "family": "鹎科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★★",
        "habitat": "城市公园、庭院、树林",
        "season": "留鸟",
        "description": "白头鹎是苏州最常见的鸟类之一，因头部白色枕羽而得名。性格活泼，常在树冠层活动，春季鸣声悦耳动听。",
        "song": "清脆悦耳的「滴沥-滴沥」声，有时连续鸣叫",
        "song_phonetic": "滴沥滴沥~滴沥滴沥~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 2,
        "name": "麻雀",
        "pinyin": "má què",
        "scientific_name": "Passer montanus",
        "english_name": "Eurasian Tree Sparrow",
        "category": "雀形目",
        "family": "文鸟科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★★",
        "habitat": "人类居住区、农田",
        "season": "留鸟",
        "description": "麻雀体型小巧，棕褐色羽毛，脸颊有黑色斑块。适应性极强，与人类生活密切相关。",
        "song": "嘈杂的「唧唧喳喳」声",
        "song_phonetic": "唧唧喳~唧唧喳~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 3,
        "name": "珠颈斑鸠",
        "pinyin": "zhū jǐng bān jiū",
        "scientific_name": "Spilopelia chinensis",
        "english_name": "Spotted Dove",
        "category": "鸽形目",
        "family": "鸠鸽科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★★",
        "habitat": "公园、庭院、树林边缘",
        "season": "留鸟",
        "description": "珠颈斑鸠因其颈部有珍珠般的黑白点斑而得名。体型修长，飞行时可见翼下的金色羽毛。",
        "song": "深沉的「咕咕-咕咕」声",
        "song_phonetic": "咕咕~咕咕~古古~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 4,
        "name": "乌鸫",
        "pinyin": "wū dōng",
        "scientific_name": "Turdus mandarinus",
        "english_name": "Chinese Blackbird",
        "category": "雀形目",
        "family": "鸫科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★★",
        "habitat": "公园、花园、林地",
        "season": "留鸟",
        "description": "乌鸫全身黑色，嘴为黄色，善于鸣唱，音色丰富多变。常在地面觅食昆虫和果实。",
        "song": "婉转动听的哨音，变化丰富",
        "song_phonetic": "喑~喑喑~喑喑喑~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 5,
        "name": "八哥",
        "pinyin": "bā gē",
        "scientific_name": "Acridotheres cristatellus",
        "english_name": "Crested Myna",
        "category": "雀形目",
        "family": "椋鸟科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★★",
        "habitat": "开阔林地、农田、城市公园",
        "season": "留鸟",
        "description": "八哥通体黑色，额羽耸立如冠，翅膀有白斑。善于模仿人声和其他鸟叫，是著名的笼养鸟。",
        "song": "响亮的「嘎嘎」声及各种模仿音",
        "song_phonetic": "嘎~嘎嘎~啦啦~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 6,
        "name": "白鹭",
        "pinyin": "bái lù",
        "scientific_name": "Egretta garzetta",
        "english_name": "Little Egret",
        "category": "鹳形目",
        "family": "鹭科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★",
        "habitat": "湿地、沼泽、池塘、河流",
        "season": "留鸟/候鸟",
        "description": "白鹭全身雪白，嘴黑色，腿细长，繁殖期头部会长出两根饰羽。常在浅水中涉行捕鱼。",
        "song": "低沉粗哑的「嘎」声",
        "song_phonetic": "嘎——",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 7,
        "name": "夜鹭",
        "pinyin": "yè lù",
        "scientific_name": "Nycticorax nycticorax",
        "english_name": "Black-crowned Night Heron",
        "category": "鹳形目",
        "family": "鹭科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★",
        "habitat": "湖泊、沼泽、红树林",
        "season": "留鸟/候鸟",
        "description": "夜鹭体型较矮，繁殖期头部和背部为蓝黑色，面部有白色纹路。顾名思义，多在黄昏和夜间活动。",
        "song": "低沉的「呱呱」声",
        "song_phonetic": "呱——呱——",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 8,
        "name": "池鹭",
        "pinyin": "chí lù",
        "scientific_name": "Ardeola bacchus",
        "english_name": "Chinese Pond Heron",
        "category": "鹳形目",
        "family": "鹭科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "池塘、稻田、沼泽",
        "season": "夏候鸟",
        "description": "池鹭繁殖期头颈胸部为栗红色，背部有灰蓝色羽毛。非繁殖期则多为淡褐色。",
        "song": "粗哑的「嘎」声",
        "song_phonetic": "嘎——",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 9,
        "name": "小鸊鷉",
        "pinyin": "xiǎo pì tī",
        "scientific_name": "Tachybaptus ruficollis",
        "english_name": "Little Grebe",
        "category": "鸊鷉目",
        "family": "鸊鷉科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★",
        "habitat": "池塘、湖泊、沼泽",
        "season": "留鸟",
        "description": "小鸊鷉体型小巧，羽毛多为棕褐色。常在水面潜水捕食，繁殖期会在水边筑浮巢。",
        "song": "尖锐的「滴滴」声",
        "song_phonetic": "滴滴~滴~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 10,
        "name": "凤头鸊鷉",
        "pinyin": "fèng tóu pì tī",
        "scientific_name": "Podiceps cristatus",
        "english_name": "Great Crested Grebe",
        "category": "鸊鷉目",
        "family": "鸊鷉科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "湖泊、池塘",
        "season": "留鸟/候鸟",
        "description": "凤头鸊鷉体型较大，头部有显著的黑色羽冠，繁殖期面部有栗红色饰羽。求偶时会表演精美的水上舞蹈。",
        "song": "低沉的「咕噜」声",
        "song_phonetic": "咕噜~咕噜~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 11,
        "name": "黑水鸡",
        "pinyin": "hēi shuǐ jī",
        "scientific_name": "Gallinula chloropus",
        "english_name": "Common Moorhen",
        "category": "鹤形目",
        "family": "秧鸡科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "池塘、湖泊、沼泽",
        "season": "留鸟",
        "description": "黑水鸡通体灰黑色，额甲红色，嘴尖黄色。善游泳，常在水面植物间穿行。",
        "song": "短促的「咯咯」声",
        "song_phonetic": "咯~咯咯~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 12,
        "name": "斑嘴鸭",
        "pinyin": "bān zuǐ yā",
        "scientific_name": "Anas zonorhyncha",
        "english_name": "Eastern Spot-billed Duck",
        "category": "雁形目",
        "family": "鸭科",
        "conservation_level": "省重点保护动物",
        "common_level": "★★★",
        "habitat": "湖泊、河流、沼泽",
        "season": "留鸟/冬候鸟",
        "description": "斑嘴鸭体型中等，嘴端黑色且基部有黄色斑块。全身褐色，有深色过眼纹。",
        "song": "沙哑的「嘎嘎」声",
        "song_phonetic": "嘎——嘎——",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 13,
        "name": "戴胜",
        "pinyin": "dài shèng",
        "scientific_name": "Upupa epops",
        "english_name": "Eurasian Hoopoe",
        "category": "犀鸟目",
        "family": "戴胜科",
        "conservation_level": "省重点保护动物",
        "common_level": "★★★",
        "habitat": "开阔林地、公园、农田",
        "season": "留鸟/候鸟",
        "description": "戴胜羽色独特，棕褐色羽毛，头顶有扇形羽冠。嘴细长下弯，常在地面觅食昆虫。",
        "song": "低沉的「扑-扑-扑」声",
        "song_phonetic": "呼呼~呼呼~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 14,
        "name": "大斑啄木鸟",
        "pinyin": "dà bān zhuó mù niǎo",
        "scientific_name": "Dendrocopos major",
        "english_name": "Great Spotted Woodpecker",
        "category": "啄木鸟目",
        "family": "啄木鸟科",
        "conservation_level": "省重点保护动物",
        "common_level": "★★★",
        "habitat": "森林、公园、树林",
        "season": "留鸟",
        "description": "大斑啄木鸟背部黑白相间，臀部红色。攀爬树干并用嘴敲击木头寻找昆虫。",
        "song": "短促的「滴滴」声及敲击声",
        "song_phonetic": "滴~滴滴~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 15,
        "name": "暗绿绣眼鸟",
        "pinyin": "àn lǜ xiù yǎn niǎo",
        "scientific_name": "Zosterops simplex",
        "english_name": "Swinhoe's White-eye",
        "category": "雀形目",
        "family": "绣眼鸟科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "公园、果园、树林",
        "season": "留鸟/候鸟",
        "description": "暗绿绣眼鸟体型小巧，眼周有白色羽圈。背部黄绿色，常在花丛中觅食花蜜和昆虫。",
        "song": "细碎的「滋滋」声",
        "song_phonetic": "滋滋滋~滋滋~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 16,
        "name": "棕背伯劳",
        "pinyin": "zōng bèi bó láo",
        "scientific_name": "Lanius schach",
        "english_name": "Long-tailed Shrike",
        "category": "雀形目",
        "family": "伯劳科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "开阔林地、农田、灌丛",
        "season": "留鸟",
        "description": "棕背伯劳体型矫健，头部灰色，背部棕色，眼罩黑色。嘴尖端带钩，性凶猛。",
        "song": "响亮的「嘎嘎」声及模仿其他鸟叫",
        "song_phonetic": "嘎——嘎——",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 17,
        "name": "画眉",
        "pinyin": "huà méi",
        "scientific_name": "Garrulax canorus",
        "english_name": "Chinese Hwamei",
        "category": "雀形目",
        "family": "噪鹛科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "丘陵林地、灌丛",
        "season": "留鸟",
        "description": "画眉因眼周白色眉纹而得名。全身棕褐色，鸣声婉转动听，是中国传统的笼养鸟之一。",
        "song": "婉转的「叽咕-叽咕」声",
        "song_phonetic": "叽咕叽咕~叽咕~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 18,
        "name": "喜鹊",
        "pinyin": "xǐ què",
        "scientific_name": "Pica pica",
        "english_name": "Eurasian Magpie",
        "category": "雀形目",
        "family": "鸦科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★",
        "habitat": "公园、村庄、林缘",
        "season": "留鸟",
        "description": "喜鹊体型较大，黑白相间的羽毛，飞行时可见蓝色光泽的翅膀。常在高大树木上筑巢。",
        "song": "响亮的「喳喳」声",
        "song_phonetic": "喳~喳喳~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 19,
        "name": "灰喜鹊",
        "pinyin": "huī xǐ què",
        "scientific_name": "Cyanopica cyanus",
        "english_name": "Azure-winged Magpie",
        "category": "雀形目",
        "family": "鸦科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★★",
        "habitat": "公园、树林、城市绿地",
        "season": "留鸟",
        "description": "灰喜鹊头部黑色，背部灰色，翅膀和尾羽为天蓝色。性格活泼，常成群活动。",
        "song": "尖锐的「滴沥」声",
        "song_phonetic": "滴~滴滴~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 20,
        "name": "白鹡鸰",
        "pinyin": "bái jí líng",
        "scientific_name": "Motacilla alba",
        "english_name": "White Wagtail",
        "category": "雀形目",
        "family": "鹡鸰科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "溪流、池塘、农田",
        "season": "留鸟/候鸟",
        "description": "白鹡鸰体型细长，全身黑白相间。尾羽常上下摆动，行走时像在跳舞。",
        "song": "清脆的「唧唧」声",
        "song_phonetic": "唧~唧唧~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 21,
        "name": "黑尾蜡嘴雀",
        "pinyin": "hēi wěi là zuǐ què",
        "scientific_name": "Eophona migratoria",
        "english_name": "Chinese Grosbeak",
        "category": "雀形目",
        "family": "燕雀科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "树林、果园、公园",
        "season": "留鸟/候鸟",
        "description": "黑尾蜡嘴雀体型圆胖，雄鸟头部黑色，雌鸟头部灰色。嘴粗大呈蜡黄色，适合咬碎种子。",
        "song": "柔和的「咕噜」声",
        "song_phonetic": "咕噜~咕噜~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 22,
        "name": "金翅雀",
        "pinyin": "jīn chì què",
        "scientific_name": "Chloris sinica",
        "english_name": "Oriental Greenfinch",
        "category": "雀形目",
        "family": "燕雀科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "公园、灌丛、农田",
        "season": "留鸟",
        "description": "金翅雀体型小巧，胸部黄绿色，翅膀有金黄色斑块。常在树枝上悬挂取食花序。",
        "song": "清脆的「铃铃」声",
        "song_phonetic": "铃~铃铃~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 23,
        "name": "燕雀",
        "pinyin": "yàn què",
        "scientific_name": "Fringilla montifringilla",
        "english_name": "Brambling",
        "category": "雀形目",
        "family": "燕雀科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "林地、公园、农田",
        "season": "冬候鸟",
        "description": "燕雀体型中等，繁殖期雄鸟头部蓝黑色，胸部橙色。冬季常成大群活动。",
        "song": "柔和的「喑喑」声",
        "song_phonetic": "喑~喑喑~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 24,
        "name": "黄腰柳莺",
        "pinyin": "huáng yāo liǔ yīng",
        "scientific_name": "Phylloscopus proregulus",
        "english_name": "Pallas's Leaf Warbler",
        "category": "雀形目",
        "family": "柳莺科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "树林、公园、灌丛",
        "season": "候鸟",
        "description": "黄腰柳莺体型极小，最显著特征是腰部有一道亮黄色纵纹。动作活泼，常在树冠层跳跃。",
        "song": "高亢的「齐齐-齐齐」声",
        "song_phonetic": "齐齐~齐齐~齐齐齐~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 25,
        "name": "黄眉柳莺",
        "pinyin": "huáng méi liǔ yīng",
        "scientific_name": "Phylloscopus inornatus",
        "english_name": "Yellow-browed Warbler",
        "category": "雀形目",
        "family": "柳莺科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "树林、公园、花园",
        "season": "候鸟",
        "description": "黄眉柳莺体型小巧，眉纹黄色，翅膀有两道白斑。春季迁徙时数量较多。",
        "song": "清脆的「飞飞-飞飞」声",
        "song_phonetic": "飞飞~飞飞~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 26,
        "name": "远东树莺",
        "pinyin": "yuǎn dōng shù yīng",
        "scientific_name": "Horornis diphone",
        "english_name": "Japanese Bush Warbler",
        "category": "雀形目",
        "family": "树莺科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "灌丛、草丛、林地边缘",
        "season": "候鸟",
        "description": "远东树莺全身棕褐色，鸣声响亮穿透力强。叫声常被比作「不如归去」。",
        "song": "悠长的「唧唧-哩哩」声",
        "song_phonetic": "唧唧~哩哩~不如归~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 27,
        "name": "北红尾鸲",
        "pinyin": "běi hóng wěi qú",
        "scientific_name": "Phoenicurus auroreus",
        "english_name": "Daurian Redstart",
        "category": "雀形目",
        "family": "鹟科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "林地、公园、灌丛",
        "season": "冬候鸟",
        "description": "北红尾鸲雄鸟头部银灰色，胸部和尾羽为鲜艳的红褐色。冬季常出现在公园和庭院。",
        "song": "清脆的「滴滴」声",
        "song_phonetic": "滴滴~滴滴~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 28,
        "name": "红头长尾山雀",
        "pinyin": "hóng tóu cháng wěi shān què",
        "scientific_name": "Aegithalos concinnus",
        "english_name": "Black-throated Tit",
        "category": "雀形目",
        "family": "长尾山雀科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "树林、公园、灌丛",
        "season": "留鸟",
        "description": "红头长尾山雀体型极小，头顶红褐色，眼部有黑色纹路。尾羽较长，常群居活动。",
        "song": "细碎的「滋滋」声",
        "song_phonetic": "滋滋滋~滋滋~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 29,
        "name": "山麻雀",
        "pinyin": "shān má què",
        "scientific_name": "Passer rutilans",
        "english_name": "Russet Sparrow",
        "category": "雀形目",
        "family": "文鸟科",
        "conservation_level": "三有保护动物",
        "common_level": "★★",
        "habitat": "山地林地、丘陵",
        "season": "留鸟",
        "description": "山麻雀体型比家麻雀稍小，雄鸟上体呈温暖的栗色。与家麻雀相比，更偏爱山地环境。",
        "song": "与家麻雀相似的「唧唧」声",
        "song_phonetic": "唧~唧唧~",
        "image_url": "",
        "audio_url": ""
    },
    {
        "id": 30,
        "name": "普通翠鸟",
        "pinyin": "pǔ tōng cuì niǎo",
        "scientific_name": "Alcedo atthis",
        "english_name": "Common Kingfisher",
        "category": "佛法僧目",
        "family": "翠鸟科",
        "conservation_level": "三有保护动物",
        "common_level": "★★★",
        "habitat": "溪流、池塘、河流",
        "season": "留鸟",
        "description": "普通翠鸟体型小巧，羽色艳丽，背部蓝色，腹部橙红色。常在水面低飞，然后俯冲入水捕鱼。",
        "song": "尖锐的「叽叽」声",
        "song_phonetic": "叽~叽叽~",
        "image_url": "",
        "audio_url": ""
    }
]
